### ISSUE TITLE
Group level folder not created

### ISSUE THREAD

**Issue by adelavega** [poldracklab/fitlins#21]
When creating the group level svg plot the following error occurs:

    FileNotFoundError: [Errno 2] No such file or directory: '/analysis/out_all2/fitlins/ses-
    perceptionTraining01/ses-perceptionTraining01_task-perception_run-1_bold_contrasts.svg'

Looks like the parent folder is never created prior to outputting the SVG, hence the error.

**Comment by effigies** [comment]
Ah. I wonder if the better thing is to drop the `session` entity altogether. Unless it's desired to keep things sorted this way? I guess it's safer to not drop, but we may want to consider that things like `ses-` and `run-` that aren't going to be collapsed and do not disambiguate outputs might add pointless verbosity.

**Comment by adelavega** [comment]
Actually I was wondering about that as well. Wouldn't it be an issue if you're analyzing multiple sessions?

**Comment by effigies** [comment]
Yes, so it would need to be dependent on whether the session is a relevant unit in later blocks. This may not be the most trivial thing to decide from many spots within a pipeline, so I'm inclined to leave it alone for now.

However, if we collapse all higher-level blocks into a single second-level, then the problem will go away. (This is my solution to everything, since it'll probably be Tal who figures out how to do it.)

**Comment by tyarkoni** [comment]
I'm not sure if that's because you have faith in my abilities or disregard for my sanity, but I find it troubling either way. ;)
