### ISSUE TITLE
Citeproc failing to install in Docker

### ISSUE THREAD

**Issue by effigies** [poldracklab/fitlins#227]
Last released on Feb 9, so may be somewhere upstream of citeproc causing the problems.

@yarikoptic have you seen this (https://circleci.com/gh/poldracklab/fitlins/2397) before?

**Comment by yarikoptic** [comment]
nope, haven't seen and not (yet) verse in citeproc and rnc2rng to immediately tell the cause.  But rnc2rng seems about to release, see https://github.com/djc/rnc2rng/issues/27 , so may be it is fixed in master?  if you could reproduce locally (for me citeproc installed fine when I tried recently) and test if it is gone with master version of rnc2rng -- would be great

**Comment by yarikoptic** [comment]
I believe it is a regression introduced in the just released rnc2rng https://github.com/djc/rnc2rng/issues/28  .

**Comment by yarikoptic** [comment]
FWIW, pushed 0.5.1 citeproc which shouldn't fail installation, please check ;)

**Comment by effigies** [comment]
Thanks, Yarik. Rerunning tests.

**Comment by effigies** [comment]
Builds fine. Thanks!
